from bot.base.resource import Template
from bot.base.common import Area, ImageMatchConfig
from module.umamusume.define import ScenarioType

UMAMUSUME_UI_TEMPLATE_PATH = "/umamusume/ui"
UMAMUSUME_BTN_TEMPLATE_PATH = "/umamusume/btn"
UMAMUSUME_REF_TEMPLATE_PATH = "/umamusume/ref"
UMAMUSUME_UMA_ICON_TEMPLATE_PATH = "/umamusume/uma_icon"
UMAMUSUME_SCENARIO_TEMPLATE_PATH = "/umamusume/scenario"

UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH = "/umamusume/ui/aoharuhai"
UMAMUSUME_REF_AOHARUHAI_TEMPLATE_PATH = "/umamusume/ref/aoharuhai"


UI_INFO = Template("INFO", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MAIN_MENU = Template("MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_MAIN_MENU = Template("CULTIVATE_MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(12, 3, 105, 38)))
UI_CULTIVATE_TRAINING_SELECT = Template("CULTIVATE_TRAINING_SELECT", UMAMUSUME_UI_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(12, 3, 105, 38)))
UI_CULTIVATE_TRAINING_ITEMS = Template("CULTIVATE_TRAINING_ITEMS", UMAMUSUME_UI_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(200, 35, 520, 65)))
UI_CULTIVATE_USE_TRAINING_ITEMS = Template("CULTIVATE_USE_TRAINING_ITEMS", UMAMUSUME_UI_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(430, 1172, 640, 1228)))
UI_CULTIVATE_TRAINING_SELECT_1 = Template("CULTIVATE_TRAINING_SELECT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SCENARIO_SELECT = Template("CULTIVATE_SCENARIO_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT = Template("CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SUPPORT_CARD_SELECT = Template("CULTIVATE_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EXTEND_UMAMUSUME_SELECT = Template("CULTIVATE_EXTEND_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_UMAMUSUME_SELECT = Template("CULTIVATE_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FINAL_CHECK = Template("CULTIVATE_FINAL_CHECK", UMAMUSUME_UI_TEMPLATE_PATH)

UI_SCENARIO_URA = Template("SCENARIO_URA", UMAMUSUME_SCENARIO_TEMPLATE_PATH)
UI_SCENARIO_AOHARUHAI = Template("SCENARIO_AOHARUHAI", UMAMUSUME_SCENARIO_TEMPLATE_PATH)
UI_SCENARIO_MANT = Template("SCENARIO_MANT", UMAMUSUME_SCENARIO_TEMPLATE_PATH)

UI_SCENARIO: dict[ScenarioType, Template] = {
    ScenarioType.SCENARIO_TYPE_UNKNOWN: None,
    ScenarioType.SCENARIO_TYPE_URA: UI_SCENARIO_URA,
    ScenarioType.SCENARIO_TYPE_AOHARUHAI: UI_SCENARIO_AOHARUHAI,
    ScenarioType.SCENARIO_TYPE_MANT: UI_SCENARIO_MANT,
}

UI_CULTIVATE_EVENT_UMAMUSUME = Template("CULTIVATE_EVENT_UMAMUSUME", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SUPPORT_CARD = Template("CULTIVATE_EVENT_SUPPORT_CARD", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SCENARIO = Template("CULTIVATE_EVENT_SCENARIO", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_GOAL_RACE_1 = Template("CULTIVATE_GOAL_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_GOAL_RACE_2 = Template("CULTIVATE_GOAL_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_1 = Template("CULTIVATE_URA_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_2 = Template("CULTIVATE_URA_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_3 = Template("CULTIVATE_URA_RACE_3", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_1 = Template("CULTIVATE_RACE_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_2 = Template("CULTIVATE_RACE_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_BEFORE_RACE_1 = Template("BEFORE_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_BEFORE_RACE_2 = Template("BEFORE_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_UMA_LIST_1 = Template("IN_RACE_UMA_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_UMA_LIST_2 = Template("IN_RACE_UMA_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_1 = Template("IN_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_2 = Template("IN_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_RACE_RESULT_1 = Template("RACE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_RESULT_2 = Template("RACE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_1 = Template("RACE_REWARD_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_2 = Template("RACE_REWARD_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_AOHARUHAI_RACE = Template("AOHARUHAI_RACE", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_1 = Template("AOHARUHAI_RACE_1", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_2 = Template("AOHARUHAI_RACE_2", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_3 = Template("AOHARUHAI_RACE_3", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_4 = Template("AOHARUHAI_RACE_4", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_5 = Template("AOHARUHAI_RACE_5", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_SELECT_OPPONENT = Template("AOHARUHAI_RACE_SELECT_OPPONENT", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_FINAL_START = Template("AOHARUHAI_RACE_FINAL_START", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_CONFIRM = Template("AOHARUHAI_RACE_CONFIRM", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_INRACE = Template("AOHARUHAI_RACE_INRACE", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_END = Template("AOHARUHAI_RACE_END", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_SCHEDULE = Template("AOHARUHAI_RACE_SCHEDULE", UMAMUSUME_UI_AOHARUHAI_TEMPLATE_PATH)

REF_AOHARUHAI_TEAM_NAME_0 = Template("AOHARUHAI_TEAM_NAME_0", UMAMUSUME_REF_AOHARUHAI_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_1 = Template("AOHARUHAI_TEAM_NAME_1", UMAMUSUME_REF_AOHARUHAI_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_2 = Template("AOHARUHAI_TEAM_NAME_2", UMAMUSUME_REF_AOHARUHAI_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_3 = Template("AOHARUHAI_TEAM_NAME_3", UMAMUSUME_REF_AOHARUHAI_TEMPLATE_PATH)

REF_AOHARUHAI_TEAM_NAME = [REF_AOHARUHAI_TEAM_NAME_0, REF_AOHARUHAI_TEAM_NAME_1,
                           REF_AOHARUHAI_TEAM_NAME_2, REF_AOHARUHAI_TEAM_NAME_3]

REF_AOHARU_RACE = Template("race_aoharu", UMAMUSUME_REF_TEMPLATE_PATH)

REF_ROUND_1 = Template("round_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_ROUND_2 = Template("round_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_ROUND_3 = Template("round_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_ROUND_4 = Template("round_4", UMAMUSUME_REF_TEMPLATE_PATH)

REF_HINT_LEVEL_1 = Template("hint_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_HINT_LEVEL_2 = Template("hint_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_HINT_LEVEL_3 = Template("hint_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_HINT_LEVEL_4 = Template("hint_4", UMAMUSUME_REF_TEMPLATE_PATH)
REF_HINT_LEVEL_5 = Template("hint_5", UMAMUSUME_REF_TEMPLATE_PATH)
REF_HINT_LEVELS = [REF_HINT_LEVEL_1, REF_HINT_LEVEL_2, REF_HINT_LEVEL_3, REF_HINT_LEVEL_4, REF_HINT_LEVEL_5]

REF_HINT_LEVELS_TEXT = Template("hintLevels", UMAMUSUME_REF_TEMPLATE_PATH,
    ImageMatchConfig(match_area=Area(205, 935, 339, 1132), match_accuracy=0.71))

UI_GOAL_ACHIEVED = Template("GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_GOAL_FAILED = Template("GOAL_FAILED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_NEXT_GOAL = Template("NEXT_GOAL", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ALL_GOAL_ACHIEVED = Template("ALL_GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_EXTEND = Template("CULTIVATE_EXTEND", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT = Template("CULTIVATE_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_1 = Template("CULTIVATE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_2 = Template("CULTIVATE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_1 = Template("CULTIVATE_CATCH_DOLL_GAME_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_2 = Template("CULTIVATE_CATCH_DOLL_GAME_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_1 = Template("CULTIVATE_CATCH_DOLL_GAME_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_2 = Template("CULTIVATE_CATCH_DOLL_GAME_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_LEARN_SKILL_1 = Template("CULTIVATE_LEARN_SKILL_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_FAIL = Template("RACE_FAIL", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEARN_SKILL_2 = Template("CULTIVATE_LEARN_SKILL_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CONFIRMATION_LEARNSKILL_BUTTON = Template("CONFIRMATION_LEARNSKILL_BUTTON", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FRIEND_RECREATION = Template("FRIEND_RECREATION", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FRIEND_RECREATION_COMPLETE = Template("FRIEND_RECREATION_COMPLETE", UMAMUSUME_UI_TEMPLATE_PATH)

UI_RECREATION_FRIEND_NOTIFICATION = Template("recreation_friend_notification", UMAMUSUME_UI_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(294, 1047, 452, 1124)))
UI_HOME_HINT = Template("home_hint", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_FINISH = Template("CULTIVATE_FINISH", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RECEIVE_CUP = Template("RECEIVE_CUP", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEVEL_RESULT = Template("CULTIVATE_LEVEL_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FACTOR_RECEIVE = Template("FACTOR_RECEIVE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_HISTORICAL_RATING_UPDATE = Template("HISTORICAL_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_SCENARIO_RATING_UPDATE = Template("SCENARIO_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_RESULT = Template("ACTIVITY_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_REWARD = Template("ACTIVITY_REWARD", UMAMUSUME_UI_TEMPLATE_PATH)

REF_SUPPORT_CARD_TYPE_SPEED = Template("SUPPORT_CARD_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_STAMINA = Template("SUPPORT_CARD_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_POWER = Template("SUPPORT_CARD_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_WILL = Template("SUPPORT_CARD_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_INTELLIGENCE = Template("SUPPORT_CARD_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_FRIEND = Template("SUPPORT_CARD_TYPE_FRIEND", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_GROUP = Template("SUPPORT_CARD_TYPE_GROUP", UMAMUSUME_REF_TEMPLATE_PATH)


REF_TRAINING_TYPE_SPEED = Template("TRAINING_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_STAMINA = Template("TRAINING_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_POWER = Template("TRAINING_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_WILL = Template("TRAINING_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_INTELLIGENCE = Template("TRAINING_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)

REF_TRAINING_HINT = Template("hint", UMAMUSUME_REF_TEMPLATE_PATH)


REF_MOTIVATION_1 = Template("MOTIVATION_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_2 = Template("MOTIVATION_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_3 = Template("MOTIVATION_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_4 = Template("MOTIVATION_4", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_5 = Template("MOTIVATION_5", UMAMUSUME_REF_TEMPLATE_PATH)

MOTIVATION_LIST = [REF_MOTIVATION_1, REF_MOTIVATION_2, REF_MOTIVATION_3, REF_MOTIVATION_4, REF_MOTIVATION_5]

REF_CULTIVATE_SUPPORT_CARD_EMPTY = Template("CULTIVATE_SUPPORT_CARD_EMPTY", UMAMUSUME_REF_TEMPLATE_PATH)
REF_FOLLOW_SUPPORT_CARD_DETECT_LABEL = Template("FOLLOW_SUPPORT_CARD_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_BORROW_CARD = Template("borrow_card", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SELECTOR = Template("SELECTOR", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_accuracy=0.72))
REF_TRAIN_BTN = Template("train_btn", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST = Template("race_list", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(23, 7, 109, 31), match_accuracy=0.83))
REF_RACE_LIST_GOAL_RACE = Template("RACE_LIST_GOAL_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_URA_RACE = Template("RACE_LIST_URA_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_DETECT_LABEL = Template("RACE_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_accuracy=0.82))
REF_SKILL_LIST_DETECT_LABEL = Template("SKILL_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SKILL_LEARNED = Template("SKILL_LEARNED", UMAMUSUME_REF_TEMPLATE_PATH)

REF_DEBUT_RACE_NOT_WIN = Template("DEBUT_RACE_NOT_WIN", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUITABLE_RACE = Template("SUITABLE_RACE", UMAMUSUME_REF_TEMPLATE_PATH)

REF_RECOVER_TP_1 = Template("RECOVER_TP_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_2 = Template("RECOVER_TP_2", UMAMUSUME_REF_TEMPLATE_PATH)

REF_RECOVER_TP_2_CARROT = Template("RECOVER_TP_2_CARROT", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_3 = Template("RECOVER_TP_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_3_CARROT = Template("RECOVER_TP_3_CARROT", UMAMUSUME_REF_TEMPLATE_PATH)

REF_TP_RECOVER_DRINK = Template("TP_RECOVER_DRINK", UMAMUSUME_REF_TEMPLATE_PATH)

REF_FACTOR_DETECT_LABEL = Template("FACTOR_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)

REF_HOME_GIFT = Template("home_gift", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(26, 602, 695, 644)))
REF_TEAM_TRIALS = Template("team_trials", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TEAM_RACE = Template("team_race", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SELECT_OPP = Template("select_opp", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SELECT_OPP2 = Template("select_opp2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_ALL_RES = Template("all_res", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_END = Template("race_end", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_END2 = Template("race_end2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TEAM_SHOWDOWN = Template("team_showdown", UMAMUSUME_REF_TEMPLATE_PATH)
REF_NEXT = Template("next", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(0, 640, 720, 1280), match_accuracy=0.79))
REF_SEE_RESULTS = Template("see_results", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RESUME_CAREER = Template("resume_career", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(548, 375, 632, 422)))
REF_NEXT2 = Template("next2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TT_SEE_ALL = Template("TT_SEE_ALL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_CANT_TT = Template("cant_tt", UMAMUSUME_REF_TEMPLATE_PATH)
REF_CANT_TT2 = Template("cant_tt2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TP = Template("tp", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(162, 32, 198, 61)))
REF_HOME_COIN = Template("home_coin", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(150, 70, 220, 120)))
REF_EDIT_TEAM = Template("edit_team", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(310, 630, 339, 657)))
REF_ENERGY = Template("energy", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(163, 149, 229, 169)))

REF_FULL_NRG = Template("fullNRG", UMAMUSUME_REF_TEMPLATE_PATH)

REF_MANT_PLUS = Template("mant_plus", UMAMUSUME_REF_TEMPLATE_PATH)

URA_DATE_1 = Template("URA_DATE_1", UMAMUSUME_REF_TEMPLATE_PATH)
URA_DATE_2 = Template("URA_DATE_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONT_CLICK = Template("DONT_CLICK", UMAMUSUME_REF_TEMPLATE_PATH)

BTN_SKIP = Template("SKIP", UMAMUSUME_BTN_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(434, 1122, 720, 1280)))
BTN_SKIP_OFF = Template("SKIP_OFF", UMAMUSUME_BTN_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(180, 1224, 333, 1271)))
BTN_SKIP_SPEED_1 = Template("SKIP_SPEED_1", UMAMUSUME_BTN_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(180, 1224, 333, 1271)))
BTN_SKIP_SPEED_2 = Template("SKIP_SPEED_2", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_CLOSE = Template("CLOSE", UMAMUSUME_BTN_TEMPLATE_PATH)

UMA_ICON_URA_NPC_1 = Template("URA_NPC_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_URA_NPC_2 = Template("URA_NPC_2", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_FRIEND_1 = Template("FRIEND_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)


UMAMUSUME_REF_MANT_SHOP_PATH = "/umamusume/ref/mantShop"

REF_TRAINING_ITEMS_BTN = Template("training_items", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MANT_ON_SALE = Template("mant_on_sale", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(392, 1062, 432, 1087)))
REF_BLUE_LINE = Template("blue_line", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MANT_FINAL_END = Template("mant_final_end", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(280, 10, 450, 90), match_accuracy=0.80))
REF_MANT_SHOP_TITLE = Template("shop_title", UMAMUSUME_REF_MANT_SHOP_PATH, ImageMatchConfig(match_area=Area(17, 8, 78, 35)))
REF_SHOP_MANT_CHECK = Template("shop_mant_check", UMAMUSUME_REF_MANT_SHOP_PATH, ImageMatchConfig(match_area=Area(23, 10, 74, 31), match_accuracy=0.83))
REF_MANT_SHOP_CHECKMARK = Template("mant_shop_checkmark", UMAMUSUME_REF_MANT_SHOP_PATH)

REF_MANT_REWARD_ITEMS = Template("items", UMAMUSUME_REF_TEMPLATE_PATH, ImageMatchConfig(match_area=Area(224, 797, 326, 817), match_accuracy=0.76))

# CNN class name -> display key mapping (no template images needed, CNN handles recognition)
MANT_SHOP_ITEM_NAMES = {
    "Aroma": "aroma",
    "Bbq": "bbq",
    "Binoc": "binoc",
    "CatFood": "catfood",
    "CureAll": "cureall",
    "EnergyDrinkLarge": "energydrinklarge",
    "EnergyDrinkMedium": "energydrinkmedium",
    "EnergyDrinkSmall": "energydrinksmall",
    "GreenJuice": "greenjuice",
    "GutsLarge": "gutslarge",
    "GutsMedium": "gutsmedium",
    "GutsPet": "gutspet",
    "GutsSmall": "gutssmall",
    "GutsWeights": "gutsweights",
    "HandCream": "handcream",
    "Hat": "hat",
    "MaxLarge": "maxlarge",
    "MaxSmall": "maxsmall",
    "MegaLarge": "megalarge",
    "MegaMedium": "megamedium",
    "MegaSmall": "megasmall",
    "Mirror": "mirror",
    "MoodLarge": "moodlarge",
    "MoodSmall": "moodsmall",
    "PenLight": "penlight",
    "Pillow": "pillow",
    "PowerLarge": "powerlarge",
    "PowerMedium": "powermedium",
    "PowerPet": "powerpet",
    "PowerSmall": "powersmall",
    "PowerWeights": "powerweights",
    "PPBook": "ppbook",
    "Prayer": "prayer",
    "Rb": "rb",
    "Rbex": "rbex",
    "Scale": "scale",
    "Scheduler": "scheduler",
    "Shuffle": "shuffle",
    "SpeedLarge": "speedlarge",
    "SpeedMedium": "speedmedium",
    "SpeedPet": "speedpet",
    "SpeedSmall": "speedsmall",
    "SpeedWeights": "speedweights",
    "StaminaLarge": "staminalarge",
    "StaminaMedium": "staminamedium",
    "StaminaPet": "staminapet",
    "StaminaSmall": "staminasmall",
    "StaminaWeights": "staminaweights",
    "Useless2": "useless2",
    "WitLarge": "witlarge",
    "WitMedium": "witmedium",
    "WitPet": "witpet",
    "WitSmall": "witsmall",
}

