TRAINING_CLICK_DELAY = 0.15
TRAINING_WAIT_DELAY = 0.12
TRAINING_RETRY_DELAY = 0.15
TRAINING_DETECTION_DELAY = 0.005

RECREATION_MENU_DELAY = 0.3
MENU_RETURN_DELAY = 0.12
MEDIC_CHECK_DELAY = 0.12

ENERGY_READ_RETRY_DELAY = 0.12

RACE_SEARCH_TIMEOUT = 30

MAX_TRAINING_RETRY = 5
MAX_DETECTION_ATTEMPTS = 3
